name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  upload_linux_binaries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'workflow.zip'
          exclusions: '*.git*'

      - name: Run a multi-line script
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload linux workflow.zip --clobber
  upload_windows_binaries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'workflow.zip'
          exclusions: '*.git*'

      - name: Run a multi-line script
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload windows workflow.zip --clobber
